version: '3.8'

services:
  stack:
    image: redis/redis-stack
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - stack_cache:/data


  extractor:
    build:
      context: .
      dockerfile: local.Dockerfile
    command: python manage.py Extractor

  transformer:
    build:
      context: .
      dockerfile: local.Dockerfile
    command: python manage.py Transformer

  loader:
    build:
      context: .
      dockerfile: local.Dockerfile
    command: python manage.py Loader


volumes:
  stack_cache:
    driver: local
